### ISSUE TITLE
get rid of animation in Bayesian machine learning lesson

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#10]
lesson: Bayesian evolution of  𝑝(𝜇|𝐷)  for the coin toss

In the simulation `Bayesian evolution of  𝑝(𝜇|𝐷)  for the coin toss` lets get rid of the animation and replace the code by code that generates four small plots that shows the evolution of the posterior, eg after 0, 1, 5, 50 tosses.

**Comment by ismailsenoz** [comment]
Instead of animation, we have 4 subplots showing the evolution of posterior.

**Comment by bertdv** [comment]
great, thx
