### ISSUE TITLE
Add Julia code to generate fig.10.6

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#12]
- Add Julia code to generate fig. 10.6 in Latent Variable lesson (https://nbviewer.jupyter.org/github/bertdv/BMLIP/blob/master/lessons/notebooks/Latent-Variable-Models-and-VB.ipynb)

- Also there is a deprecation warning in another piece of code. Please fix.

**Comment by bertdv** [comment]
This is now working in a branch vgmm and needs to get ported to master. (with the activation scripts).  @magnus can you take a look at this?

**Comment by wmkouw** [comment]
PR was rejected. Instead, the figure was added to master in commit 04077b0dabbed5826e80589c803dc82af84f6991
