### ISSUE TITLE
Add an illustrative example of active inference to the intelligent agent lesson

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#14]
eg Thijs's mountain car, Magnus' BATMAN or Burak' robot. Preferably coded in FL.

**Comment by wmkouw** [comment]
@MagnusKoudahl, we can just take the code from the BATMAN paper. It's mostly FL, right? A small part is Turing. 

Burak's robot is impressive, but I have no idea what he has put in there. Thijs' code has this 'act-execute-observe' structure, which I'm not sure is suitable; we would have to explain what he means with that.

**Comment by bertdv** [comment]
The (1) act-execute-observe, (2) infer the next control/action, (3) slide forward structure of Thijs is needed for online active inference, but I do teach that idea in the class so it does make it very suitable I think.

**Comment by MagnusKoudahl** [comment]
I would be wary of using BATMAN as a first exposure. There is some weirdness with the binary feedback that means it takes a very large number of iterations to converge and does "jumps".
Buraks robot runs basically identical code and it's showing similar issues.

For a good demonstrator, my money would be on Thijs' Mountain Car. Act-Execute-Observe is not difficult to move from helper functions and into the main notebook if we want.

**Comment by MagnusKoudahl** [comment]
@bertdv the three steps in that order are not strictly necessary. BATMAN and the Generalised FE paper both run a different order

**Comment by bertdv** [comment]
Not strictly but in that order but these it does provide a nice way of structuring the computations.

**Comment by wmkouw** [comment]
Alright. Thijs' mountain car seems like the more suited option. 

Thijs' code is archived [here](https://github.com/biaslab/ActiveInferenceExperiments), right?
@Magnus, did you already check with Thijs whether this is up-to-date? I can ask him today.

**Comment by MagnusKoudahl** [comment]
I haven't checked with him yet. I've fiddled around with the notebooks a bit this morning and there seem to be some minor bugs - nothing we can't handle with a little bit of elbow grease though.
