### ISSUE TITLE
todo: installation guide for Julia and Jupyter

### ISSUE THREAD

**Issue by wmkouw** [bertdv/BMLIP#20]
I think we (read: I) should write an installation guide so that the students can quickly install the right versions of Julia and Jupyters. Lots of things can go wrong in the PP notebooks if they get their versions wrong.

**Comment by MagnusKoudahl** [comment]
Didn't we use to have one somewhere? It boils down to 

1. Install julia from website (v 1.3)
2. Install Jupyter notebooks through preferred medium
3. Pkg.add("IJulia")

Packages etc is in the manifest

**Comment by wmkouw** [comment]
It does boil down to that. But I've added commands and checks to help the students perform these steps. 

PR just came in via biaslab-hugo.
