### ISSUE TITLE
Show parts of MCMCChain

### ISSUE THREAD

**Issue by wmkouw** [bertdv/BMLIP#22]
Currently, I'm using the following command to inspect the MCMC chain in the HMM notebook.
```
describe(chain)
```
However, this produces a lot of output. I actually just want to inspect the chains for some of the latter states. I need to find a way of indexing the chain, something like:
```
describe(chain[:x_40 : :x_50])
```

**Comment by MagnusKoudahl** [comment]
I believe there's a chain.value or similar to get the output of the sampler directly. Would that do it for what you need?

**Comment by wmkouw** [comment]
Found it:
```
chain["x[1]"]
```

When you index the chain with strings, you can get specific entries of a vector or matrix. But you cannot get multiple indices that way. 
`chain["x[1:2]"` won't work, for obvious reasons.
