### ISSUE TITLE
move lectures to .jmd and pluto

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#28]
Use jmd to write the lectures, then export to various formats. 

eg see workflow in https://github.com/mitmath/18S191

Use pluto.jl rather than jupyter ipynb notebooks. Static display with github's htmlpreview, eg

https://htmlpreview.github.io/?https://github.com/mitmath/18S191/blob/master/homework/homework0/hw0.html

**Comment by wmkouw** [comment]
I tried making a Pluto version of the probabilistic programming notebooks, but Pluto and ForneyLab never really went well together. Now that we're on ReactiveMP, it might be interesting to try again.

Fons is coming to the [Julia meetup Nov 22](https://www.meetup.com/julialang-in-the-netherlands/events/289347929/). I could try Pluto again and ask him for help if I run into weird bugs again?
