### ISSUE TITLE
Code issue in Latent Variable lesson

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#33]
There is a (Julia) code issue in the latent variable lecture notes:

https://github.com/bertdv/BMLIP/blob/master/lessons/notebooks/Latent-Variable-Models-and-VB.ipynb

Has to do with pre-compilation of `CSV.jl`. Could anybody please fix this ASAP? thanks!

**Comment by MagnusKoudahl** [comment]
I can't reproduce this on my end. Maybe we can figure it out if we take a look at the stacktrace and your local environment?

**Comment by bertdv** [comment]
manifest.toml update fixed teh issue. thanks!
