### ISSUE TITLE
code issue in Factor graph notebook

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#36]
there is a "dangling edge" problem w the code in the Factor graph notebook. I think there has been an update to FL so this can be fixed. 

The notebook 

https://nbviewer.jupyter.org/github/bertdv/BMLIP/blob/master/lessons/notebooks/Factor-Graphs.ipynb

does nto show it yet (at least not for me).

**Comment by MagnusKoudahl** [comment]
Updated manifest with ForneyLab v0.11.2
