### ISSUE TITLE
URL link from notebook to a page in pdf

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#4]
I would like to put links in the lecture notes to a specific page in a pdf file (eg the PRML book). It should be possible for a student to click on a link in the notebook and a specific page from the PRML book opens. This way we can make notes such as

for proof, see [Bishop, p.463](URL). 

I have looked around and it should be possible to add a named bookmark (say with name `p463`) and make it work with a link such as 

`https://github.com/bertdv/BMLIP/blob/master/lessons/notebooks/files/PRML.pdf#p463`

but it does not work for me. Can any of you figure out how to make this work?

**Comment by wmkouw** [comment]
Do you still want this, Bert? It was in my todo-list, but I gave it low priority (I was going to work on it after we finished the PP notebooks).

**Comment by MagnusKoudahl** [comment]
It's closed right?

**Comment by bertdv** [comment]
No, this is fine now.  thx
