### ISSUE TITLE
upgrade all notebooks to julia 1.8 and make sure everything runs

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#40]
@Sepideh-Adamiat B0-B6
@abpolym B7-B12

**Comment by abpolym** [comment]
Lessons `B00-B11` work with a Julia `1.8.2` kernel that uses the `lessons/Project.toml` environment.

Issue can be closed as soon as

* `B12` notebook runs given the correct (older) ForneyLab version (require: update `lessons/Project.toml`)
