### ISSUE TITLE
please check if generating pdf files works

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#41]
instructions for generating PDF files: 

https://github.com/bertdv/BMLIP/blob/master/bundler/instructions.txt

code in `bundler` folder. 

outputs in `output` folder.

**Comment by bertdv** [comment]
Hi @Sepideh-Adamiat can you please update me on the status of this issue?

**Comment by Sepideh-Adamiat** [comment]
Hi @bertdv with Julia 1.7 the bundler is working. I will check it with Julia 1.8, and then I will push my changes in bundler.py.

**Comment by bertdv** [comment]
Hi @Sepideh-Adamiat great, please do a git pull first to make sure you work on the latest code of the master branch.

**Comment by Sepideh-Adamiat** [comment]
Hi @bertdv , The pull command is done and now the branch is up-to-date.

**Comment by Sepideh-Adamiat** [comment]
I changed the Bundler's kernel to Julia 1.8 .

**Comment by bertdv** [comment]
When it's all ready, can you do a pull request, so I can merge w master?

**Comment by Sepideh-Adamiat** [comment]
I fixed the merge conflict and merged it with the master.

**Comment by bertdv** [comment]
Thanks you. So, this issue can be closed?

**Comment by Sepideh-Adamiat** [comment]
Yes, I will close it.
