### ISSUE TITLE
Point lecture notes links of 2021-22 landing page to correct versions. 

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#42]
The lecture notes and exercises at the landing page for 2021-22 (https://biaslab.github.io/teaching/archive/bmlip-2021/) point to the most recent versions (Not the versions of 2021-22). Please fix.

**Comment by abpolym** [comment]
Resolved:

- All links (notebooks, exercises, downloads) in the [2021-22 teaching tab](https://biaslab.github.io/teaching/archive/bmlip-2021/) which previously pointed to the master commit now point to the [tagged commit](https://github.com/bertdv/BMLIP/tree/a75b6f0f12fa393cfdd61526052ee42559f01f4e).
