### ISSUE TITLE
Factor graph Lesson still contains ForneyLab code

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#47]
Please remove ForneyLab dependence and instead use ReactiveMP.
![Screen Shot 2022-10-11 at 14 57 36](https://user-images.githubusercontent.com/3426064/195096962-9ea7ac6b-07ea-4ccd-a7f4-c726ffcaec32.png)

**Comment by abpolym** [comment]
ForneyLab has been replaced with ReactiveMP by @Sepideh-Adamiat in the Factor Graph lesson
