### ISSUE TITLE
Update Project.toml

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#48]
Is the `Project.toml` file up to date? I may not understand how `Project.toml` (and I m sorry if i say nonsense here) but I see dependency on `ForneyLab` (shouldn't this be removed?), and no dependency on `reactiveMP`

![Screen Shot 2022-10-11 at 15 00 24](https://user-images.githubusercontent.com/3426064/195097786-028f60b6-76ea-44ad-b2a1-5bb478653ec2.png)

Also, in the Gaussian distributions lesson, I see a dependency on the `hCubature` package, and get an error, but I don't see the `hCubature` package listed in `Project.toml`

<img width="744" alt="Screen Shot 2022-10-11 at 15 03 43" src="https://user-images.githubusercontent.com/3426064/195098673-eb622dcc-8f3d-4df4-99a4-831636c5d95b.png">

In teh Discriminative classification lesson, I get an error since teh `Optim` package is not found: 

<img width="610" alt="Screen Shot 2022-10-11 at 17 17 48" src="https://user-images.githubusercontent.com/3426064/195132178-8ac6b9ae-2b04-4383-a857-72ae08071556.png">

In principle, the notebooks should run for anybody who has installed Julia. 
Please update the `Project.toml` file.

**Comment by abpolym** [comment]
can be closed as soon as the updated Probabilistic Programming notebooks
* use the `lessons/Project.toml` file
* are merged into master

**Comment by wouterwln** [comment]
@abpolym could we not remove the dependency on ForneyLab? The idea is to migrate everything to ReactiveMP, right?

**Comment by bertdv** [comment]
@wouterwln teh code in the intelligent agents lecture notes uses an example of a FEP agent encoded in ForneyLab. We will keep using it for teh coming lecture series and substitute by a ReactiveMP example in the Nov 2023 year.

**Comment by bertdv** [comment]
@abpolym can this issue be closed now?
