### ISSUE TITLE
Code in latent variable models doesnt run

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#50]
Dont know why but I get an error. Please check

![Screen Shot 2022-10-12 at 13 59 14](https://user-images.githubusercontent.com/3426064/195341227-79dfd29c-e0c6-4fba-ab55-9d8f392c926a.png)

**Comment by abpolym** [comment]
Resolved: runs in `Julia 1.8.2` with the `lessons/Project.toml` environment.
