### ISSUE TITLE
Make KL divergence visualization

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#51]
Can you please code the following visualization of a KL divergence in Julia?

https://www.linkedin.com/feed/update/urn:li:activity:6990419006671179776/?utm_source=share&utm_medium=member_android

I would like to add it to the latent variable models lession, see 

https://github.com/bertdv/BMLIP/blob/master/lessons/notebooks/Latent-Variable-Models-and-VB.ipynb

**Comment by wouterwln** [comment]
@bertdv for me this link is broken. Maybe it was posted by a private account?

**Comment by bertdv** [comment]
how about this: https://bekaykang.github.io/posts/KL_divergence/
