### ISSUE TITLE
Remove `ipad-notes`?

### ISSUE THREAD

**Issue by wmkouw** [bertdv/BMLIP#60]
There are some files in folders that are perhaps outdated. For example, the folder `lessons/notebooks/ipad-notes` with 1 small [pdf](https://github.com/bertdv/BMLIP/blob/master/lessons/notebooks/ipad-notes/5SSD0-ipad-notes-ML-1.pdf). Shall we remove it?

**Comment by bertdv** [comment]
I added this file since it is a print-out of notes that I go over in a video. Please dont remove this file. I will have a look at the files that I authored that can be removed, but please only remove files that you authored or commited.

**Comment by wmkouw** [comment]
Ah, I thought it was outdated. But then that clarifies it. Shall I close the issue?

I didn't intend to remove it without consultation.
