### ISSUE TITLE
pdf generation for exercises fail

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#63]
I ran `jupyter nbconvert --config bundler/bundle_configuration.py` for the exercises and got the following:

![Screen Shot 2022-11-01 at 13 39 01](https://user-images.githubusercontent.com/3426064/199234855-a83b4b75-741a-4220-8726-fa70bdc919cb.png)

Is this a problem on my computer, or do yo get the same error?

**Comment by Sepideh-Adamiat** [comment]
I checked, and it works for me. The cause of the problem may be removing one of the notebooks. If you want to change the number or the order of them, I should change the bundler.py a bit.
