### ISSUE TITLE
phantomjs.exe appears both in root folder and ./bundler folder

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#64]
do we need `phantomjs.exe` in both folders?

**Comment by Sepideh-Adamiat** [comment]
I ran the bundler while the phantomjs.jl on the main folder was deleted, and it worked. So we don't need it in both folders.

**Comment by bertdv** [comment]
OK please fix it on the main branch and close the issue. thanks!

**Comment by Sepideh-Adamiat** [comment]
Done.
