### ISSUE TITLE
fix Julia code example in prob theory lesson

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#8]
Please fix the code examples in PT lesson. There is an error talking about WebIO, see attached. I installed WebIO but it still doesnt work. Probably remove the animation to make it work? 

- Note,  also fix this for the Bayesian machine learning lesson, and please check the other lessons as well. This seems to be an issue with the `@animate` feature in my jupyter notebooks. I have no problem with getting rid of the animations if that solves the problem.

![Screenshot](https://user-images.githubusercontent.com/3426064/72678928-be503400-3aaa-11ea-9fab-06f88d51c6f2.png)

**Comment by MagnusKoudahl** [comment]
Should be fixed by #8ca18863560ad24deb15846814e3a7d9e46279e9
For future reference WebIO needs to be fixed at v 0.7.0 for plots to render correctly in notebooks..

**Comment by bertdv** [comment]
The pretty CSS rendering appears to be gone now in probabibility theory lesson.
