### ISSUE TITLE
generate PDFs of lecture notes

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#81]
Please generate PDFs of all lecture notes and replace the old ones. The new PDFs should be accessible from the links at the homepage https://biaslab.github.io/teaching/bmlip/ .

**Comment by bertdv** [comment]
Hi @Sepideh-Adamiat -- The new generated PDF misses some plots, eg pages 18, 21, 32, 95 and perhaps more. I get the impression that, if the code for generating the plot takes a long time (eg > 15 seconds), then the PDF generator skips teh plot and moves on. If there is a timer in the generating code, can you try to increase the time? Perhaps there is another reason. Can you investigate? thanks.

**Comment by Sepideh-Adamiat** [comment]
Hi @bertdv . I fixed the problem. It was related to the kernel version. The new PDFs are pushed to the "pdf2024" branch.

**Comment by bertdv** [comment]
Hi @Sepideh-Adamiat the chapters in the PDF of the lecture notes are not in the right order. Can you please generate the PDF with chapters in right order? And please check the PDF yourself in detail before committing. thanks
