### ISSUE TITLE
update link to 5SSD0 at BIASlab homepage

### ISSUE THREAD

**Issue by bertdv** [bertdv/BMLIP#95]
Please update the link to 5SSD0 from BIASlab homepage. To make it simpler, let's no longer link to previous years, but rather have one link to "5SSD0 (Q2-2024)", under the "teaching" menu item.

![Screenshot 2024-10-02 at 10 44 37](https://github.com/user-attachments/assets/79865b4b-3287-4d0a-af13-37acb914d46c)

**Comment by abpolym** [comment]
Resolved
